todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.home, name="project_home"),
    path("todo/", include("todoapp.urls")),
    path("signup/", views.user_signup, name="signup")
]


########### The URLconf for /accounts is the django default one. It maps the below routes automatically.
########### The templates for these routes need to be created though
# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']

todo/todoapp/urls.py
from django.urls import path
from . import views

app_name = "todoapp"
urlpatterns = [
    path("", views.home, name="home"),
    path("add_task", views.add_task, name="add_task"),              
    path("mark_task", views.mark_task, name="mark_task"), 
    path("add_sub_task", views.add_sub_task, name="add_sub_task"),  
    path("delete_task", views.delete_task, name="delete_task"),
    path("task", views.TaskView.as_view(), name="task")
    # path("<int:question_id>/", views.detail, name="detail"),
    # path("<int:question_id>/results", views.results, name="results"),
    # path("<int:question_id>/vote", views.vote, name="vote")
    
]

todo/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone
import datetime

# Create your models here.

# task model -  user_id, title, due_date


class TimeStampedModel(models.Model):

    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseTask(TimeStampedModel):

    title = models.CharField(max_length=200)
    is_completed = models.BooleanField(default=False)

    is_deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(blank=True, null=True)

    def soft_delete(self):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    def mark_complete(self):
        self.is_completed = True
        self.save()

    def mark_pending(self):
        self.is_completed = False
        self.save()

    class Meta:
        abstract = True


class Task(BaseTask):

    PRIORITY_CHOICES = (
        (1, "Low"),
        (2, "Medium"),
        (3, "High"),
        (4, "Urgent")
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    due_date = models.DateField()
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['due_date']


class SubTask(BaseTask):

    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/todoapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from .models import Task, SubTask
import datetime
from dateutil import parser as date_parser
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@login_required
def home(request):
    filter_type = request.GET.get("filter", "")
    today = datetime.date.today()
    start_week =  today - datetime.timedelta(today.weekday())
    end_week = start_week + datetime.timedelta(6)
    start_nextweek =  end_week + datetime.timedelta(1)
    end_nextweek = start_nextweek + datetime.timedelta(6)

    if filter_type == "All":
        todo_list = Task.objects.filter(user=request.user, is_deleted=False)
    elif filter_type == "this_week":
        todo_list = Task.objects.filter(user=request.user, is_deleted=False, due_date__range=[start_week, end_week])
    elif filter_type == "next_week":
        todo_list = Task.objects.filter(user=request.user, is_deleted=False, due_date__range=[start_nextweek, end_nextweek])
    elif filter_type == "overdue":
        todo_list = Task.objects.filter(user=request.user, is_deleted=False, is_completed=False, due_date__lt=today)
    else:
        todo_list = Task.objects.filter(user=request.user, is_deleted=False, due_date=today)

    context = {
        'title': 'Todo-App',
        'todo_list': todo_list
    }
    # my_template = loader.get_template("polls/home.html")
    # return HttpResponse(my_template.render(context, request))
    return render(request, "todoapp/home.html", context)

@login_required
def add_task(request):
    response_dict = {}
    if request.method == "POST":
        title = request.POST.get("title","NO_TITLE")
        due_date = request.POST.get("due_date", str(datetime.date.today()))
        # due_date = date_parser.parse(due_date)
        due_date = due_date.split("GMT")[0]
        due_date = datetime.datetime.strptime(due_date.strip(), "%a %b %d %Y %H:%M:%S")
        #print(type(due_date))
        task = Task(user= request.user, title=title, due_date=due_date)
        task.save()
        response_dict["status"] = "OK"
        return HttpResponse(json.dumps(response_dict))
    else:
        response_dict["status"] = "FAIL"
        response_dict["error"] = "BAD_METHOD"
        return HttpResponse(json.dumps(response_dict))


@login_required
def mark_task(request):
    response_dict = {}
    if request.method == "POST":
        task_id = request.POST.get("id","")
        task = Task.objects.filter(id=task_id, user=request.user, is_deleted=False).first()
        if task is None :
            response_dict["status"] = "FAIL"
            response_dict["error"] = "TASK_DOES_NOT_EXIST"
        else:
            is_completed = request.POST.get("is_completed", "FALSE")
            # print(type(is_completed)) --> always str
            # print(is_completed)
            if is_completed=="TRUE" and not task.is_completed:
                task.mark_complete()
            else:
                task.mark_pending()
            task.save()
            response_dict["status"] = "OK"
    else:
        response_dict["status"] = "FAIL"
        response_dict["error"] = "BAD_METHOD"
    return HttpResponse(json.dumps(response_dict))



@login_required
def add_sub_task(request):
    response_dict = {}
    if request.method == "POST":
        task_id = request.POST.get("task_id", "")
        user = request.user
        task = Task.objects.filter(id=task_id, user=request.user, is_deleted=False).first()
        if task is None :
            response_dict["status"] = "FAIL"
            response_dict["error"] = "TASK_DOES_NOT_EXIST"
        else:
            if request.POST.get("multiple", "TRUE") == "TRUE" :
                sub_tasks = request.POST.get("sub_tasks", "")
                for each in json.loads(sub_tasks):
                    # print(each)
                    # print(type(each))
                    sub_task = SubTask(task= task, title= each["title"])
                    sub_task.save()
                response_dict["status"] = "OK"
            else:
                sub_task = request.POST.get("sub_task", "")
                sub_task_obj = SubTask(task= task, title= sub_task["title"])
                sub_task_obj.save()
                response_dict["status"] = "OK"
    else:
        response_dict["status"] = "FAIL"
        response_dict["error"] = "BAD_METHOD"
    return HttpResponse(json.dumps(response_dict))


@login_required
def delete_task(request):
    response_dict = {}
    if request.method == "POST":
        task_id = request.POST.get("id","")
        task = Task.objects.filter(id=task_id, user=request.user, is_deleted=False).first()
        if task is None :
            response_dict["status"] = "FAIL"
            response_dict["error"] = "TASK_DOES_NOT_EXIST"
        else:
            task.soft_delete()
            task.save()
            response_dict["status"] = "OK"
    else:
        response_dict["status"] = "FAIL"
        response_dict["error"] = "BAD_METHOD"
    return HttpResponse(json.dumps(response_dict))


from django.utils.decorators import method_decorator
from django.views.generic import View
from django.contrib.auth.decorators import login_required

# the decorator will be passed to / applied over the 'dispatch' function of the class.
# dispatch() handles request when .as_view() is called upon CBVs
@method_decorator(decorator=login_required, name='dispatch')
class TaskView(View):

    # show details of a task
    def get(self, request, *args, **kwargs):
        return HttpResponse(request.method)

    # add a new task
    def post(self, request, *args, **kwargs):
        return HttpResponse(request.method)

    # update a task
    def put(self, request, *args, **kwargs):
        return HttpResponse(request.method)

    # delete a task
    def delete(self, request, *args, **kwargs):
        return HttpResponse(request.method)

todo/todoapp/templates/todoapp/home.html
{% extends "todoapp/base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <br>
        <p style="font-size: 24px;">Tasks</p>

        <div class="row">
        <div class="col-md-12">

          <div class="col-md-8">
            <input class="form-control" id="search_input" type="text" placeholder="Search Tasks ...">
          </div>

          <div class="col-md-1" align="">
                <button class="btn" id="add_task_btn" data-toggle="modal" data-target="#add_task_modal"  >Add Task</button>
              </div>

          <div class="col-md-1">

            <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" >
                        <span id="dropdown_text" type= "text"></span>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="?filter=All">All</a></li>
                        <li><a class="dropdown-item" href="?filter=today">Today</a></li>
                        <li><a class="dropdown-item" href="?filter=overdue">Overdue</a></li>
                        <li><a class="dropdown-item" href="?filter=this_week">This week</a></li>
                        <li><a class="dropdown-item" href="?filter=next_week">Next week</a></li>
                    </ul>
            </div>


          </div>


        </div>
        </div>



    </div>

    <br>

    <!-- -------------- accordion below ------------- -->

    {% if todo_list %}

    <div class="panel-group" id="accordion">

        {% for todo in todo_list %}

        <div class="panel panel-default" id="hey{{forloop.counter}}">
            <div class="panel-heading" {% if todo.is_completed %} style="background:#e9e6e6;" {% endif %} >
                <div class="row">
                <div class="col-md-12">
                    <div class="col-md-8 panel2" id="hey{{forloop.counter}}_title">
                       <h4 class="panel-title"  >
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{forloop.counter}}"  {% if todo.is_completed %} style="color:#807e7eda;" {% endif %}   >
                            <strong>{{ todo.title }}</strong>
                        </a>

                       </h4>

                    </div>
                    <div class="col-md-1">
                        {% if todo.subtask_set.all %}
                        <span class="label label-warning">{{todo.subtask_set.count}} subtasks</span>
                        {% endif %}
                    </div>
                    <div class=" row col-md-3" align="end">
                        {% if todo.is_completed %}
                        <span class="label label-default">Completed</span>
                        <span class="label label-default">{{ todo.due_date }}</span>
                        {% else %}
                        <span class="label label-success">Pending</span>
                        <span class="label label-success">{{ todo.due_date }}</span>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>

            <div id="collapse{{forloop.counter}}" class="panel-collapse collapse">
                <div class="panel-body">
                    {% if todo.subtask_set.all %}
                    <ul>
                       {% for subt in todo.subtask_set.all %}
                       <li>{{subt.title}}</li>
                       {% endfor %}
                    </ul>
                    {% else %}
                    <p>No sub-tasks to show.</p>
                    {% endif %}
                    <button class="btn btn-sm addsubtask" id="{{todo.id}}" data-toggle="modal" data-target="#add_sub_task_modal">Add Sub-tasks</button>
                </div>
                <div class="panel-footer" align="end">
                    {% if not todo.is_completed %}
                    <button class="btn btn-success marktask" id="done_{{todo.id}}">Mark Complete</button>
                    {% else %}
                    Task Done. <a class="marktask" id="undone_{{todo.id}}" href="#">Mark as Pending</a>
                    {% endif %}
                    <button class="btn btn-danger deletetask" id="{{todo.id}}"><i class="fa fa-trash" aria-hidden="true" style="font-size:18px;"></i></button>


                </div>

            </div>
        </div>
        <br>

    {% endfor %}
    </div>
    {% else %}
    <p>No tasks to do.</p>
    {% endif %}










<!--
    {% if todo_list %}

    {% for todo in todo_list %}
        <a href="#">{{ todo }}</a>
    {% endfor %}
    {% else %}
    <p>No tasks to do.</p>
    {% endif %} -->




</div>



<!-- modal add task here  -->

<div id="add_task_modal" class="modal fade" >
        <div class="modal-dialog">
                <div class="modal-content">



                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add new task</h4>
                    </div>

                    <div class="modal-body">



                        <form id="" action="/" method="post">

                            <div class="row">
                                <div class="input-field col-md-12">
                                    <label for="title_inp">Task Title : </label>
                                    <input  id="title_inp" type="text" class=" form-control validate" placeholder="Enter Task Title" maxlength="198">
                                </div>
                            </div>

                            <br>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-field inline">
                                        <label for="due_date_inp" >Due date : </label>
                                    <input  id="due_date_inp" type="date" class=" form-control validate" placeholder="Due date for task">
                                    </div>
                                </div>
                            </div>


                        </form>



                    </div>

                    <div class="modal-footer">
                        <button type="button" id="add_task_submit" class="btn btn-default">Submit</button>
                    </div>


                </div>

        </div>
    </div>


    <!-- --------- add SUB-TASK modal below ----------- -->




<div id="add_sub_task_modal" class="modal fade" >
    <div class="modal-dialog">
            <div class="modal-content">



                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Sub-tasks</h4>
                </div>

                <div class="modal-body">

                    <p>Sub-tasks :</p>
                    <div class="input_fields_wrap">
                        <input type="text" name="answer[]" class="field-long form-control" placeholder="Enter sub-task ..." maxlength="198" style="margin-bottom: 4px;"/>
                    </div>

                    <br>
                    <button class="btn btn-sm btn-primary add_field_button">Add another sub-task</button>
                    <button class="btn btn-sm btn-danger remove_field_button">Remove sub-task</button>

                    <input id="task_id_for_subtask" type="text" class="validate" hidden>

                </div>

                <div class="modal-footer">
                    <button type="button" id="add_sub_task_submit" class="btn btn-default">Save</button>
                </div>


            </div>

    </div>
</div>












{% endblock %}